#!/usr/bin/with-contenv bash

#set permission
chmod +x /opt/script.sh

#check if cron interval is set. Add cron interval if not set. Dont add if is set already
if grep -q script.sh /etc/crontabs/root; then
  echo "Interval already set skipping...."
else
  echo "---setup cron---"
  echo "$croninterval /opt/script.sh" >> /etc/crontabs/root
fi

